=== turbolent/embergraph/embergraph-util/src/test/java/com/bigdata/testutil/Experiment.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- This is the required root element and describes an experiment comprised of experimental conditions.  Conditions should be varied so as to test the effect of various parameters on interesting behaviors of the system.  -->
<!ELEMENT experiment ((defaults)?, (condition)*)>
<!-- @class is the name of a Java class to be run that implements IComparisonTest. -->
<!ATTLIST experiment
	class CDATA #REQUIRED
>
<!-- Default properties are inherited by each condition and may be overriden within a given condition. -->
<!ELEMENT defaults (property)*>
<!-- An experimental condition is comprised properties that are interpreted as a configuration to be tested. -->
<!ELEMENT condition ((property)*, (result)*)>
<!ELEMENT property (#PCDATA)>
<!ATTLIST property
	name CDATA #REQUIRED
>
<!-- The result element makes it possible to serialize the results of the experiment as an experiment XML file. -->
<!ELEMENT result (#PCDATA)>
<!ATTLIST result
	name CDATA #REQUIRED
>

=== turbolent/embergraph/embergraph-core-test/bigdata/src/test/org/embergraph/concurrent/TestLockManager.xml
<?xml version="1.0" ?>
<!DOCTYPE experiment PUBLIC "-//systap.com//DTD BIGDATA EXPERIMENT 0.1//EN" "Experiment.dtd">
<experiment class="com.bigdata.concurrent.TestLockManager">
 <defaults>
  <property name="ntasks">1000</property>
  <property name="maxLocks">3</property>
  <property name="lockTimeout">1000</property>
  <property name="minLocks">1</property>
  <property name="nthreads">20</property>
  <property name="maxLockTries">1</property>
  <property name="testTimeout">30</property>
  <property name="nresources">100</property>
 </defaults>
 <condition>
  <property name="nthreads">2</property>
 </condition>
 <condition>
 </condition>
 <condition>
  <property name="percentTaskDeath">.10</property>
 </condition>
 <condition>
  <property name="nthreads">100</property>
 </condition>
 <condition>
  <property name="nthreads">100</property>
  <property name="percentTaskDeath">.10</property>
 </condition>
 <condition>
  <property name="maxLocks">1</property>
  <property name="nresources">1</property>
 </condition>
 <condition>
  <property name="minLocks">3</property>
  <property name="nresources">3</property>
 </condition>
</experiment>

=== turbolent/embergraph/embergraph-core-test/bigdata/src/test/com/bigdata/journal/StressTestGroupCommit2.xml
<?xml version="1.0" ?>
<!DOCTYPE experiment PUBLIC "-//systap.com//DTD BIGDATA EXPERIMENT 0.1//EN" "Experiment.dtd">
<!-- There are 4 conditions. -->
<experiment class="com.bigdata.journal.StressTestGroupCommit">
 <defaults>
  <property name="maximumExtent">419430400</property>
  <property name="timeout">5</property>
  <property name="createTempFile">true</property>
  <property name="ntasks">10000</property>
 </defaults>
 <condition>
  <property name="writeServiceQueueCapacity">500</property>
  <property name="bufferMode">Disk</property>
  <property name="writeServiceMaximumPoolSize">500</property>
  <property name="writeServiceCorePoolSize">500</property>
 </condition>
 <condition>
  <property name="writeServiceQueueCapacity">1000</property>
  <property name="bufferMode">Disk</property>
  <property name="writeServiceMaximumPoolSize">1000</property>
  <property name="writeServiceCorePoolSize">1000</property>
 </condition>
 <condition>
  <property name="writeServiceQueueCapacity">1500</property>
  <property name="bufferMode">Disk</property>
  <property name="writeServiceMaximumPoolSize">1500</property>
  <property name="writeServiceCorePoolSize">1500</property>
 </condition>
 <condition>
  <property name="writeServiceQueueCapacity">2000</property>
  <property name="bufferMode">Disk</property>
  <property name="writeServiceMaximumPoolSize">2000</property>
  <property name="writeServiceCorePoolSize">2000</property>
 </condition>
</experiment>

=== turbolent/embergraph/embergraph-core-test/bigdata/src/test/com/bigdata/journal/StressTestConcurrentTx.xml
<?xml version="1.0" ?>
<!DOCTYPE experiment PUBLIC "-//systap.com//DTD BIGDATA EXPERIMENT 0.1//EN" "Experiment.dtd">
<!-- There are 48 conditions. -->
<experiment class="com.bigdata.journal.StressTestConcurrentTx">
 <defaults>
  <property name="maximumExtent">419430400</property>
  <property name="timeout">30</property>
  <property name="abortRate">.05</property>
  <property name="createTempFile">true</property>
  <property name="ntrials">10000</property>
  <property name="keyLen">4</property>
  <property name="bufferMode">Disk</property>
 </defaults>
 <condition>
  <property name="nclients">1</property>
  <property name="nops">1</property>
 </condition>
 <condition>
  <property name="nclients">10</property>
  <property name="nops">1</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="nops">1</property>
 </condition>
 <condition>
  <property name="nclients">50</property>
  <property name="nops">1</property>
 </condition>
 <condition>
  <property name="nclients">100</property>
  <property name="nops">1</property>
 </condition>
 <condition>
  <property name="nclients">200</property>
  <property name="nops">1</property>
 </condition>
 <condition>
  <property name="nclients">1</property>
  <property name="nops">10</property>
 </condition>
 <condition>
  <property name="nclients">10</property>
  <property name="nops">10</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="nops">10</property>
 </condition>
 <condition>
  <property name="nclients">50</property>
  <property name="nops">10</property>
 </condition>
 <condition>
  <property name="nclients">100</property>
  <property name="nops">10</property>
 </condition>
 <condition>
  <property name="nclients">200</property>
  <property name="nops">10</property>
 </condition>
 <condition>
  <property name="nclients">1</property>
  <property name="nops">100</property>
 </condition>
 <condition>
  <property name="nclients">10</property>
  <property name="nops">100</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="nops">100</property>
 </condition>
 <condition>
  <property name="nclients">50</property>
  <property name="nops">100</property>
 </condition>
 <condition>
  <property name="nclients">100</property>
  <property name="nops">100</property>
 </condition>
 <condition>
  <property name="nclients">200</property>
  <property name="nops">100</property>
 </condition>
 <condition>
  <property name="nclients">1</property>
  <property name="nops">1000</property>
 </condition>
 <condition>
  <property name="nclients">10</property>
  <property name="nops">1000</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="nops">1000</property>
 </condition>
 <condition>
  <property name="nclients">50</property>
  <property name="nops">1000</property>
 </condition>
 <condition>
  <property name="nclients">100</property>
  <property name="nops">1000</property>
 </condition>
 <condition>
  <property name="nclients">200</property>
  <property name="nops">1000</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">1</property>
  <property name="nops">1</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">10</property>
  <property name="nops">1</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">20</property>
  <property name="nops">1</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">50</property>
  <property name="nops">1</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">100</property>
  <property name="nops">1</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">200</property>
  <property name="nops">1</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">1</property>
  <property name="nops">10</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">10</property>
  <property name="nops">10</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">20</property>
  <property name="nops">10</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">50</property>
  <property name="nops">10</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">100</property>
  <property name="nops">10</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">200</property>
  <property name="nops">10</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">1</property>
  <property name="nops">100</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">10</property>
  <property name="nops">100</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">20</property>
  <property name="nops">100</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">50</property>
  <property name="nops">100</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">100</property>
  <property name="nops">100</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">200</property>
  <property name="nops">100</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">1</property>
  <property name="nops">1000</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">10</property>
  <property name="nops">1000</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">20</property>
  <property name="nops">1000</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">50</property>
  <property name="nops">1000</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">100</property>
  <property name="nops">1000</property>
 </condition>
 <condition>
  <property name="keyLen">8</property>
  <property name="nclients">200</property>
  <property name="nops">1000</property>
 </condition>
</experiment>

=== turbolent/embergraph/embergraph-cache/src/test/java/org/embergraph/cache/StressTestGlobalLRU.xml
<?xml version="1.0" ?>
<!DOCTYPE experiment PUBLIC "-//systap.com//DTD BIGDATA EXPERIMENT 0.1//EN" "Experiment.dtd">
<!-- There are 4 conditions. -->
<experiment class="com.bigdata.cache.lru.StressTestGlobalLRU">
 <defaults>
  <property name="com.bigdata.LRUNexus.minCacheSetSize">0</property>
  <property name="com.bigdata.LRUNexus.initialCapacity">16</property>
  <property name="com.bigdata.LRUNexus.loadFactor">.75</property>
  <property name="com.bigdata.LRUNexus.maxHeap">10240</property>
  <property name="com.bigdata.LRUNexus.percentCleared">.25</property>
  <property name="nthreads">3</property>
  <property name="testTimeout">20</property>
  <property name="com.bigdata.LRUNexus.concurrencyLevel">16</property>
  <property name="nops">10000000000</property>
 </defaults>
 <!-- condition#1 -->
 <condition>
  <property name="com.bigdata.LRUNexus.class">com.bigdata.cache.lru.BCHMGlobalLRU2</property>
  <property name="com.bigdata.LRUNexus.threadLocalBuffers">false</property>
  <property name="com.bigdata.LRUNexus.threadLocalBufferCapacity">128</property>
  <property name="com.bigdata.LRUNexus.accessPolicy">LRU</property>
 </condition>
 <condition>
  <property name="com.bigdata.LRUNexus.class">com.bigdata.cache.lru.BCHMGlobalLRU2</property>
  <property name="com.bigdata.LRUNexus.threadLocalBuffers">true</property>
  <property name="com.bigdata.LRUNexus.threadLocalBufferCapacity">128</property>
  <property name="com.bigdata.LRUNexus.accessPolicy">LRU</property>
 </condition>
 <!-- condition#2 
 <condition>
  <property name="com.bigdata.LRUNexus.class">com.bigdata.cache.lru.BCHMGlobalLRU2</property>
  <property name="com.bigdata.LRUNexus.threadLocalBuffers">false</property>
  <property name="com.bigdata.LRUNexus.threadLocalBufferCapacity">128</property>
  <property name="com.bigdata.LRUNexus.accessPolicy">LIRS</property>
 </condition>
 <condition>
  <property name="com.bigdata.LRUNexus.class">com.bigdata.cache.lru.BCHMGlobalLRU2</property>
  <property name="com.bigdata.LRUNexus.threadLocalBuffers">true</property>
  <property name="com.bigdata.LRUNexus.threadLocalBufferCapacity">128</property>
  <property name="com.bigdata.LRUNexus.accessPolicy">LIRS</property>
 </condition>
 -->
 <!-- infinispan cache implementations : these cause problems in the CI builds 
 <condition>
  <property name="com.bigdata.LRUNexus.class">com.bigdata.cache.lru.BCHMGlobalLRU</property>
  <property name="com.bigdata.LRUNexus.accessPolicy">LRU</property>
 </condition>
 <condition>
  <property name="com.bigdata.LRUNexus.class">com.bigdata.cache.lru.BCHMGlobalLRU</property>
  <property name="com.bigdata.LRUNexus.accessPolicy">LIRS</property>
 </condition>
-->
</experiment>

=== turbolent/embergraph/embergraph-core-test/bigdata/src/test/org/embergraph/journal/StressTestMRMW.xml
<?xml version="1.0" ?>
<!DOCTYPE experiment PUBLIC "-//systap.com//DTD BIGDATA EXPERIMENT 0.1//EN" "Experiment.dtd">
<experiment class="com.bigdata.journal.AbstractMRMWTestCase$StressTestMRMW">
 <defaults>
  <property name="maximumExtent">419430400</property>
  <property name="timeout">30</property>
  <property name="createTempFile">true</property>
  <property name="nreads">100</property>
  <property name="nwrites">100</property>
  <property name="ntrials">100000</property>
  <property name="reclen">1024</property>
  <property name="percentReaders">.8</property>
 </defaults>
 <condition>
  <property name="nclients">20</property>
  <property name="bufferMode">Transient</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="bufferMode">Direct</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="bufferMode">Direct</property>
  <property name="forceOnCommit">No</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="bufferMode">Disk</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="bufferMode">Disk</property>
  <property name="forceOnCommit">No</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="bufferMode">Transient</property>
  <property name="timeout">10</property>
  <property name="percentReaders">0.0</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="bufferMode">Direct</property>
  <property name="timeout">10</property>
  <property name="percentReaders">0.0</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="bufferMode">Direct</property>
  <property name="timeout">10</property>
  <property name="forceOnCommit">No</property>
  <property name="percentReaders">0.0</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="bufferMode">Disk</property>
  <property name="timeout">10</property>
  <property name="percentReaders">0.0</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="bufferMode">Disk</property>
  <property name="timeout">10</property>
  <property name="forceOnCommit">No</property>
  <property name="percentReaders">0.0</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="bufferMode">Transient</property>
  <property name="timeout">10</property>
  <property name="percentReaders">1.0</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="bufferMode">Direct</property>
  <property name="timeout">10</property>
  <property name="percentReaders">1.0</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="bufferMode">Direct</property>
  <property name="timeout">10</property>
  <property name="forceOnCommit">No</property>
  <property name="percentReaders">1.0</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="bufferMode">Disk</property>
  <property name="timeout">10</property>
  <property name="percentReaders">1.0</property>
 </condition>
 <condition>
  <property name="nclients">20</property>
  <property name="bufferMode">Disk</property>
  <property name="timeout">10</property>
  <property name="forceOnCommit">No</property>
  <property name="percentReaders">1.0</property>
 </condition>
</experiment>

=== turbolent/embergraph/embergraph-cache/src/test/java/com/bigdata/cache/TestHardReferenceQueueWithBatchingEvictions.xml
<?xml version="1.0" ?>
<!DOCTYPE experiment PUBLIC "-//systap.com//DTD BIGDATA EXPERIMENT 0.1//EN" "Experiment.dtd">
<!-- There are 20 conditions. -->
<experiment class="com.bigdata.cache.TestHardReferenceQueueWithBatchingUpdates">
 <defaults>
  <property name="capacity">8000</property>
  <property name="threadLocalNScan">0</property>
  <property name="units">SECONDS</property>
  <property name="timeout">10</property>
 </defaults>
 <!-- condition#1 -->
 <condition>
  <property name="threadLocalCapacity">16</property>
  <property name="nthreads">1</property>
  <property name="threadLocalTryLockSize">8</property>
 </condition>
 <!-- condition#2 -->
 <condition>
  <property name="threadLocalCapacity">16</property>
  <property name="nthreads">2</property>
  <property name="threadLocalTryLockSize">8</property>
 </condition>
 <!-- condition#3 -->
 <condition>
  <property name="threadLocalCapacity">16</property>
  <property name="nthreads">4</property>
  <property name="threadLocalTryLockSize">8</property>
 </condition>
 <!-- condition#4 -->
 <condition>
  <property name="threadLocalCapacity">16</property>
  <property name="nthreads">8</property>
  <property name="threadLocalTryLockSize">8</property>
 </condition>
 <!-- condition#5 -->
 <condition>
  <property name="threadLocalCapacity">16</property>
  <property name="nthreads">16</property>
  <property name="threadLocalTryLockSize">8</property>
 </condition>
 <!-- condition#6 -->
 <condition>
  <property name="threadLocalCapacity">32</property>
  <property name="nthreads">1</property>
  <property name="threadLocalTryLockSize">16</property>
 </condition>
 <!-- condition#7 -->
 <condition>
  <property name="threadLocalCapacity">32</property>
  <property name="nthreads">2</property>
  <property name="threadLocalTryLockSize">16</property>
 </condition>
 <!-- condition#8 -->
 <condition>
  <property name="threadLocalCapacity">32</property>
  <property name="nthreads">4</property>
  <property name="threadLocalTryLockSize">16</property>
 </condition>
 <!-- condition#9 -->
 <condition>
  <property name="threadLocalCapacity">32</property>
  <property name="nthreads">8</property>
  <property name="threadLocalTryLockSize">16</property>
 </condition>
 <!-- condition#10 -->
 <condition>
  <property name="threadLocalCapacity">32</property>
  <property name="nthreads">16</property>
  <property name="threadLocalTryLockSize">16</property>
 </condition>
 <!-- condition#11 -->
 <condition>
  <property name="threadLocalCapacity">64</property>
  <property name="nthreads">1</property>
  <property name="threadLocalTryLockSize">32</property>
 </condition>
 <!-- condition#12 -->
 <condition>
  <property name="threadLocalCapacity">64</property>
  <property name="nthreads">2</property>
  <property name="threadLocalTryLockSize">32</property>
 </condition>
 <!-- condition#13 -->
 <condition>
  <property name="threadLocalCapacity">64</property>
  <property name="nthreads">4</property>
  <property name="threadLocalTryLockSize">32</property>
 </condition>
 <!-- condition#14 -->
 <condition>
  <property name="threadLocalCapacity">64</property>
  <property name="nthreads">8</property>
  <property name="threadLocalTryLockSize">32</property>
 </condition>
 <!-- condition#15 -->
 <condition>
  <property name="threadLocalCapacity">64</property>
  <property name="nthreads">16</property>
  <property name="threadLocalTryLockSize">32</property>
 </condition>
 <!-- condition#16 -->
 <condition>
  <property name="threadLocalCapacity">128</property>
  <property name="nthreads">1</property>
  <property name="threadLocalTryLockSize">64</property>
 </condition>
 <!-- condition#17 -->
 <condition>
  <property name="threadLocalCapacity">128</property>
  <property name="nthreads">2</property>
  <property name="threadLocalTryLockSize">64</property>
 </condition>
 <!-- condition#18 -->
 <condition>
  <property name="threadLocalCapacity">128</property>
  <property name="nthreads">4</property>
  <property name="threadLocalTryLockSize">64</property>
 </condition>
 <!-- condition#19 -->
 <condition>
  <property name="threadLocalCapacity">128</property>
  <property name="nthreads">8</property>
  <property name="threadLocalTryLockSize">64</property>
 </condition>
 <!-- condition#20 -->
 <condition>
  <property name="threadLocalCapacity">128</property>
  <property name="nthreads">16</property>
  <property name="threadLocalTryLockSize">64</property>
 </condition>
</experiment>
